//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icarus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssertion
    {
        public int IDAssertion { get; set; }
        public string Description { get; set; }
        public int IDAdmission { get; set; }
        public System.DateTime AssertionDate { get; set; }
        public int IDAssertionCategory { get; set; }
        public decimal Qty { get; set; }
        public decimal Price { get; set; }
        public decimal Markup { get; set; }
        public decimal MarkupValue { get; set; }
        public decimal SubTotal { get; set; }
        public string Notes { get; set; }
        public Nullable<int> IDChargeToCodep { get; set; }
        public System.DateTime PostedDate { get; set; }
    }
}
