//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icarus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdmissionBilling
    {
        public int IDAdmissionBilling { get; set; }
        public int IDAdmission { get; set; }
        public System.DateTime BillingDate { get; set; }
        public System.DateTime GeneratedDate { get; set; }
        public decimal Amount { get; set; }
        public string Notes { get; set; }
        public System.DateTime PostedDate { get; set; }
        public string GeneratedBy { get; set; }
    }
}
