//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icarus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAttachment
    {
        public int IDAttachment { get; set; }
        public string Description { get; set; }
        public string Filename { get; set; }
        public byte[] UploadedFile { get; set; }
        public Nullable<int> IDReference { get; set; }
        public string TableName { get; set; }
    }
}
