//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icarus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExpensesForAssertion
    {
        public int IDChargeToCodep { get; set; }
        public Nullable<System.DateTime> ChargeDate { get; set; }
        public Nullable<int> IDAssertionCategory { get; set; }
        public int IDExpense { get; set; }
        public string Description { get; set; }
    }
}
