//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icarus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInquiry
    {
        public int IDInquiry { get; set; }
        public Nullable<System.DateTime> InquiryDate { get; set; }
        public string Codep { get; set; }
        public string ContactNo { get; set; }
        public string Prospect { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> FollowupOn { get; set; }
        public short IDInquiryStatus { get; set; }
    }
}
