//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icarus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInquiryCommLog
    {
        public int IDInquiryCommLog { get; set; }
        public int IDInquiry { get; set; }
        public System.DateTime CommDate { get; set; }
        public string InitiatedBy { get; set; }
        public string CommDetails { get; set; }
    }
}
