//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icarus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResident
    {
        public int IDResident { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string Nickname { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<int> Age { get; set; }
        public string Sex { get; set; }
        public string Codep { get; set; }
        public string Relationship { get; set; }
        public string ContactNumber { get; set; }
        public string EmailAddress { get; set; }
    }
}
