//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icarus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRequest
    {
        public int IDRequest { get; set; }
        public System.DateTime DateRequest { get; set; }
        public Nullable<System.DateTime> DateNeeded { get; set; }
        public string RequestedBy { get; set; }
        public string Request { get; set; }
        public decimal Budget { get; set; }
        public string ApprovedBy { get; set; }
        public short IDRequestStatus { get; set; }
        public string ApproverNotes { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public string RequestorEmail { get; set; }
        public Nullable<System.DateTime> DateAcc { get; set; }
        public string RequestorNotes { get; set; }
    }
}
