//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icarus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCashAdvancePaymentBrowse
    {
        public int IDPayment { get; set; }
        public int IDCA { get; set; }
        public decimal AmountPaid { get; set; }
        public string Notes { get; set; }
        public string IsVerified { get; set; }
        public System.DateTime DatePaid { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
    }
}
