//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icarus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vExpensesBrowse
    {
        public int IDExpense { get; set; }
        public Nullable<System.DateTime> ExpenseDate { get; set; }
        public Nullable<System.DateTime> DatePosted { get; set; }
        public string ORNumber { get; set; }
        public int IDVendor { get; set; }
        public string Vendor { get; set; }
        public string Particulars { get; set; }
        public string WithReceipt { get; set; }
        public int IDAccount { get; set; }
        public string AccountCode { get; set; }
        public string Account { get; set; }
        public string EncodedBy { get; set; }
        public string IsVerified { get; set; }
        public string ChargeToCodep { get; set; }
        public decimal Amount { get; set; }
        public decimal ChargedToCodep { get; set; }
        public System.DateTime PostedDate { get; set; }
        public string TIN { get; set; }
    }
}
