//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icarus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPaymentBrowse
    {
        public int IDPayment { get; set; }
        public System.DateTime PostedDate { get; set; }
        public string Resident { get; set; }
        public int IDResident { get; set; }
        public System.DateTime PaidDate { get; set; }
        public int IDAdmission { get; set; }
        public decimal TotalPaid { get; set; }
        public Nullable<short> IDPaymentMethod { get; set; }
        public string PaymentMethod { get; set; }
        public string Bank { get; set; }
        public string CheckNo { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string Notes { get; set; }
        public string IsVerified { get; set; }
    }
}
