//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icarus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrptAssertionSummary
    {
        public string Resident { get; set; }
        public System.DateTime AssertionDate { get; set; }
        public System.DateTime PostedDate { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public decimal Qty { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public decimal Markup { get; set; }
        public decimal MarkupValue { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public decimal SubTotal { get; set; }
    }
}
