//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icarus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRSCollectible
    {
        public int IDAdmission { get; set; }
        public Nullable<int> IDResident { get; set; }
        public string Resident { get; set; }
        public System.DateTime AdmissionDate { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public decimal TreatmentFee { get; set; }
        public decimal TotalBilling { get; set; }
        public decimal TotalPaid { get; set; }
        public decimal OverallBalance { get; set; }
        public string IsActive { get; set; }
        public string LastPaymentInfo { get; set; }
    }
}
