//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icarus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRSCodepUpdate
    {
        public int IDUpdate { get; set; }
        public System.DateTime DateUpdate { get; set; }
        public System.DateTime DateLog { get; set; }
        public string UpdateType { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdateSummary { get; set; }
        public int IDAdmission { get; set; }
        public string Resident { get; set; }
    }
}
